### ISSUE TITLE
Aren't selfbots banned from discord?

### ISSUE THREAD

**Issue by Wist9063** [RayzrDev/SharpBot#116]
> Selfbot Use on Discord
Selfbots (aka self bots, self-bots) are bot code that runs under a user account and only respond with commands to the user account it's run on. Selfbots do not react to others in any way.
Selfbots are, and always have been, against the Discord API terms of use and by extension, the Discord Terms of Service, since Bot accounts were created. This position has not changed.
Source: Automating normal user accounts (generally called "self-bots") outside of the OAuth2/bot API is forbidden, and can result in an account termination if found. https://discordapp.com/developers/docs/topics/oauth2
Discord's enforcement of the selfbot policy has not changed either in the last year. If you decide to use a selfbot you do so at your own risk of getting your account banned from the API and Discord. API restrictions on selfbots are tight, any sort of abuse will be immediately dealt with. 
Note: Userbots (aka user bots, user-bots) which spam, respond to others, react to others, welcome users, etc, are dealt with swiftly and immediately. You can report userbots to abuse@discordapp.com.

Just a head's up because of the new TOS change.
This was also form DDevs server.

**Comment by tilda** [comment]
They're a gray area.

**Comment by Rayzr522** [comment]
As long as the Discord devs show favoritism and let [evie.codes](https://github.com/eslachance) use a selfbot *in from of them* ("because we trust her"), I'm going to use one too. I could rant for hours on how unprofessional that is, but I will save you the headache. 

They're a rather dark gray area, but Discord doesn't actively go around on witch hunts to ban users they suspect are using selfbots. Don't do stupid things, don't mass-DM, don't change your game every 2 seconds, and don't try to be evil. Follow those simple rules, and you're pretty much good. The people who get banned for using selfbots are usually the ones who use them in front of Discord staff, or do something malicious/spammy with them.

**Comment by s4neforlife** [comment]
☝️
